import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import SectionTitle from '../components/SectionTitle';
const posts = [
    { id: 'post-1', title: 'Caring For Your Gold Jewellery', date: 'Aug 2024', excerpt: 'Simple at–home steps to keep your gold looking radiant and lustrous.', image: '/assets/blog/care.jpg' },
    { id: 'post-2', title: 'Hallmarking – What It Really Means', date: 'Jul 2024', excerpt: 'Understanding BIS hallmark and why it protects your purchase.', image: '/assets/blog/hallmark.jpg' },
    { id: 'post-3', title: 'Styling Layered Chains', date: 'Jun 2024', excerpt: 'Balance proportions, textures & pendants for a curated layered look.', image: '/assets/blog/chains.jpg' }
];
export const BlogTeasersSection = () => (_jsx("section", { id: "blog", className: "section-padding bg-gradient-to-b from-primary-cream/50 to-white", children: _jsxs("div", { className: "max-content", children: [_jsx(SectionTitle, { title: "From Our Journal", subtitle: "Insights" }), _jsx("div", { className: "grid md:grid-cols-3 gap-8", children: posts.map(p => (_jsxs("article", { className: "group rounded-xl overflow-hidden border border-accent-gold/30 bg-white/70 backdrop-blur shadow-sm hover:shadow-lg transition", children: [_jsx("div", { className: "aspect-video w-full bg-gradient-to-br from-neutral-200 to-neutral-100 flex items-center justify-center text-xs text-neutral-500", children: _jsx("span", { children: "Image Placeholder" }) }), _jsxs("div", { className: "p-5 flex flex-col h-full", children: [_jsx("p", { className: "text-[11px] uppercase tracking-widest text-brand-red mb-2", children: p.date }), _jsx("h3", { className: "font-semibold font-serif text-lg mb-2 group-hover:text-accent-gold transition-colors", children: p.title }), _jsx("p", { className: "text-sm text-neutral-600 mb-4 line-clamp-3", children: p.excerpt }), _jsx("button", { className: "mt-auto text-xs font-semibold tracking-wide text-brand-red hover:underline focus:outline-none focus-visible:ring focus-visible:ring-brand-red/40 self-start", children: "Read More" })] })] }, p.id))) })] }) }));
export default BlogTeasersSection;
